### ISSUE TITLE
IWYU Output not reproducible via CLI

### ISSUE THREAD

**Issue by EloWork** [helly25/vscode-iwyu#18]
I have f.ex this in my output
```
2024-07-10 17:54:42.369 [trace] IWYU Command: include-what-you-use -Xiwyu --max_line_length=80  -Xiwyu --no_fwd_decls -Xiwyu --mapping_file=/mnt/work/psmgmt/scripts/psmgmt.imp [...includes defines and more...] -o .libs/psreservation.o ../../../lib/pscommon/psreservation.c 2>&1
2024-07-10 17:54:42.511 [trace] IWYU output:

(../../../include/psreservation.h has correct #includes/fwd-decls)

../../../lib/pscommon/psreservation.c should add these lines:
#include "stdbool.h"   // for false, bool, true

../../../lib/pscommon/psreservation.c should remove these lines:

The full include-list for ../../../lib/pscommon/psreservation.c:
#include "psreservation.h"
#include <stdlib.h>    // for NULL, free
#include "list.h"      // for __list_add
#include "pscommon.h"  // for PSC_log
#include "stdbool.h"   // for false, bool, true
---
```
However if I copy that command and execute it myself I see a different output
```
$ include-what-you-use [...same as in the log...]
(../../../include/psreservation.h has correct #includes/fwd-decls)

(../../../lib/pscommon/psreservation.c has correct #includes/fwd-decls)
```

**Comment by EloWork** [comment]
I found out that the output is actually from `iwyu_tool.py` and not from `include-what-you-use`. Maybe just fix the log output so that this is clea.

**Comment by helly25** [comment]
When you say "I copy that command and execute it myself" you mean you run the exact command line as vscode posted in the logs?

Assuming that is what you did, then, for prosperity and record keeping:

There are still many differences that can occur.

1) VSCode can technically run on a different computer, I assume you would know and have checked for it.
2) You can have different PATH settings leading to different binaries.
3) A number of other environment variables influence how these tools work together. They can be present in your shell, be created by VSCode, your VSCode start scripts if any or even the build system. Any of those can influence how any of the tools involved work.
4) You may have multiple iwyu and/or compiler versions installed. The PATH order and other settings (see 3) can influence which tools are used at the end.
5) There is the `iwyu.include-what-you-use` setting that controls which tool to use. The trace-level logging prints exactly what will be run in a sub-process, so you can see that. In your case above it showed that the setting was still the default. But it can still be a wrapper or alias that eventually executes something else. And that can still be different from running the same on the commandline for the any of the prior points.

How to sort out the mess:
* Create a wrapper script that shows the environment when called, e.g.:
```.sh
#!/bin/bash
set -eux
env
which include-what-you-use
include-what-you-use "${@}"
```
* In the extension settings point to that wrapper script using `iwyu.include-what-you-use`.
* If that does not help you can try to do similar things with the other involved tools (e.g. compilers).
* Try removing mapping files and anything else the tools are known to access.
* Clear any caches you may have from building (things like `~/.cache` and whatever your setup may use).

In my own setups I often find inconsistencies due to wrapper scripts I actually cannot avoid and so I have given up on running the tool in different ways. I mostly use the command line only to experiment with flags for the tools but that you can also via the extension settings which are reloaded after every change.

Hope this helps.

**Comment by EloWork** [comment]
I updated iwyu 0.21 -> 0.22 and the problems are gone. So this issue is not on the extension side. And I don't want to invest more time in finding out what even happened yesterday. The 0.21 version seems a bit buggy. Anyway thanks for the debug recommendations
